### ISSUE TITLE
self.act = self.__getattribute__(config['action']) error

### ISSUE THREAD

**Issue by peterSZW** [AlphaCat00/PyBaiduPan#1]
ENV: conda Python 3.8

pip install PyBaiduPan
pan.py
```
from pyBaiduPan import BdPan

pan = BdPan()
pan.config['app_id'] = 11111# change some configuration
pan.login('xxxx', 'xxxx')  # login
pan.list('/')
#pan.download('/test/1.jpg', './download')  # download
#pan.upload('./backup', '/test', overwrite='mtime', delete_extra=True)  # sync up
# ... or other class methods of BdPan
```
python pan.py

Traceback (most recent call last):
  File "pan.py", line 3, in <module>
    pan = BdPan()
  File "e:\ProgramData\Anaconda3\lib\site-packages\pyBaiduPan\bdpan.py", line 28, in __init__
    self.act = self.__getattribute__(config['action'])
KeyError: 'action'

**Comment by Mad-Devil** [comment]
Sorry, I forgot to add default "action" in DEFAULT_CONFIG. 
Simple work around:
```
from pyBaiduPan import BdPan
from pyBaiduPan.config import DEFAULT_CONFIG


DEFAULT_CONFIG['action'] = None
pan = BdPan()
````
This bug will be fixed in next version.
