### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by PaddyPang** [AlphaCat00/PyBaiduPan#5]
```
2021-03-09 16:47:22,603 - ERROR: 'NoneType' object has no attribute 'group'
fail due to 'NoneType' object has no attribute 'group
```
System: Big Sur 11.2.3
Python: 3.9.1

**Comment by Mad-Devil** [comment]
This is a bug caused by [DecryptLogin](https://github.com/CharlesPikachu/DecryptLogin), which pybaidupan uses to login to Baidu Pan. It seems that Baidu changed their login interface, which caused the problem.  When I have time,  I may be able to figure out a walkaround.

**Comment by AlphaCat00** [comment]
a walkaround: c1c4cc5dbd1a2abe71a92aff2356d7458dd6a284
